routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');

    // Registration Routes...
    if (config('auth.users.registration')) {
        Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'RegisterController@register');
    }

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.reset.request');

    // Confirmation Routes...
    if (config('auth.users.confirm_email')) {
        Route::get('confirm/{user_by_code}', 'ConfirmController@confirm')->name('confirm');
        Route::get('confirm/resend/{user_by_email}', 'ConfirmController@sendEmail')->name('confirm.send');
    }

    // Social Authentication Routes...
    Route::get('social/redirect/{provider}', 'SocialLoginController@redirect')->name('social.redirect');
    Route::get('social/login/{provider}', 'SocialLoginController@login')->name('social.login');
});

/**
 * Backend routes
 */
// Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

//     // Dashboard
//     Route::get('/', 'DashboardController@index')->name('dashboard');

//     //Users
//     Route::get('users', 'UserController@index')->name('users');
//     Route::get('users/{user}', 'UserController@show')->name('users.show');
//     Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
//     Route::put('users/{user}', 'UserController@update')->name('users.update');
//     Route::get('users/{user}/delete', 'UserController@destroy')->name('users.delete');
//     Route::get('permissions', 'PermissionController@index')->name('permissions');
//     Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');
//     Route::get('dashboard/log-chart', 'DashboardController@getLogChartData')->name('dashboard.log.chart');
//     Route::get('dashboard/registration-chart', 'DashboardController@getRegistrationChartData')->name('dashboard.registration.chart');
// });


Route::get('/', 'HomeController@index')->name('index');
Route::get('/inquiries', 'InquiriesController@index')->name('inquiries');
Route::get('/book', 'BookController@index')->name('book');
Route::get('/profile', 'ProfileController@index')->name('profile');
Route::post('/detail_save', 'ProfileController@detail_save');
Route::post('/address_save', 'ProfileController@store_address');

Route::get('/skateboard-deck-configurator', 'ConfiguratorController@index')->name('get.skateboard.configurator');
Route::get('/skateboard-deck-configurator/{id}', 'ConfiguratorController@show')->name('show.skateboard.configurator');
Route::post('/skateboard-deck-configurator/{id}/copy', 'ConfiguratorController@copy')->name('copy.skateboard.configurator');
Route::get('/skateboard-remove/{id}', 'ConfiguratorController@delete')->name('delete.skateboard.configurator');
Route::post('/skateboard-deck-configurator', 'ConfiguratorController@store');

Route::get('/getdesign','ConfiguratorController@getdesign');
Route::post('/configurator-fileupload', 'ConfiguratorController@upload');

Route::get('/skateboard-deck-manufacturer', 'ManufacturerController@index')->name('skateboard.manufacturer');
Route::get('/export_csv','SummaryController@exportcsv')->name('export.invoice');
Route::get('/export_csv/{id}','SummaryController@exportcsvbyid')->name('export.csv.id');
Route::get('/submit_order','SummaryController@submitOrder')->name('orders.submit');
Route::get('/save_order', 'SummaryController@saveOrder');
Route::get('/remove_saveorder/{id}','SummaryController@removeOrder');
Route::get('/getdata','HomeController@getData');

Route::get('/summary', 'SummaryController@index')->name('summary');
Route::get('/summary/{id}', 'SummaryController@load');
Route::get('/summary/view/{id}', 'SummaryController@view');
Route::get('/imprint', 'ImprintController@index');
Route::get('/ordersuccess', 'OrdersuccessController@index')->name('ordersuccess');
Route::get('/affiliate','AffiliateController@index');
Route::get('/newsletter','NewsController@index')->name('newsletter');
Route::get('/samples','SamplesController@index')->name('samples');
Route::get('/about','AboutController@index')->name('about');
Route::get('/skateboardfaq','SkateboardFAQController@index')->name('skateboardfaq');
Route::get('/invest','investController@index')->name('invest');

Route::get('/skateboard-griptape-manufacturer', 'GripTapeConfigurator@manufacturer')->name('griptape.manufacturer');
Route::get('/grip-tape-configurator', 'GripTapeConfigurator@index')->name('griptape.index');
Route::post('/grip-tape-configurator', 'GripTapeConfigurator@store')->name('griptape.store');
Route::get('/grip-tape-configurator/{id}', 'GripTapeConfigurator@show')->name('griptape.show');
Route::get('/grip-tape-remove/{id}', 'GripTapeConfigurator@destroy')->name('griptape.destroy');
Route::post('/grip-tape-configurator/{id}/copy', 'GripTapeConfigurator@copy')->name('griptape.copy');

/**
 * WHEELS CONFIGURATOR
 */
Route::group(['as' => 'wheels.'], function () {
    Route::get('/skateboard-wheels-manufacturer', 'WheelController@manufacturer')->name('manufacturer');
    Route::get('/skateboard-wheels-configurator', 'WheelController@configurator')->name('configurator');
    Route::get('/skateboard-wheels-configurator/{id}', 'WheelController@show')->name('configurator.show');
    Route::post('/skateboard-wheels-configurator', 'WheelController@storeConfigurator')->name('configurator.store');
    Route::post('/skateboard-wheels-configurator/{id}', 'WheelController@updateConfigurator')->name('configurator.update');
    Route::get('/skateboard-wheels-remove/{id}/', 'WheelController@destroy')->name('configurator.delete');
    Route::post('/skateboard-wheels-configurator/{id}/copy', 'WheelController@copy')->name('configurator.copy');

});

/**
 * HEAT TRANSFERS CONFIGURATOR
 */
Route::group(['as' => 'heat-transfer.'], function () {
    Route::get('/skateboard-heat-transfer-manufacturer', 'HeatTransferController@manufacturer')->name('manufacturer');
    Route::get('/skateboard-heat-transfer-configurator', 'HeatTransferController@configurator')->name('configurator');
});

/**
 * Membership
 */
Route::group(['as' => 'protection.'], function () {
    Route::get('membership', 'MembershipController@index')->name('membership')->middleware('protection:' . config('protection.membership.product_module_number') . ',protection.membership.failed');
    Route::get('membership/access-denied', 'MembershipController@failed')->name('membership.failed');
    Route::get('membership/clear-cache/', 'MembershipController@clearValidationCache')->name('membership.clear_validation_cache');
});


Route::group(['prefix' => 'blog', 'as' => 'blog.', 'middleware' => 'auth'], function () {
    // Route::get('/', 'BlogController@index')->name('index');
    Route::get('/create', 'BlogController@create')->name('create');
    Route::post('/', 'BlogController@store')->name('store');
    Route::delete('/{post}', 'BlogController@destroy')->name('destroy');
    Route::get('/{post}/edit', 'BlogController@edit')->name('edit');
    Route::put('/{post}', 'BlogController@update')->name('update');
});
Route::get('/blog/{id}', 'BlogController@show')->name('blog.show');


Route::post('/vendor-code', 'SummaryController@applyPromocode')->name('vendor.code.apply');

resources/views/about.blade.php
@extends('layouts.app')

@section('title', 'ABOUT 2HEX SKATEBOARD MANUFACTURER')

@push('head.meta')
    <meta name="description" content="2HEX skateboard factory. A skateboard manufacturer of skateboard decks, skateboard wheels, skateboard griptapes and high quality complete skateboards.">

	<meta name="keywords" content="2hex, skateboard, skateboard manufacturer, skateboard supplier, skateboard factory, manufacturer, supplier, factory, skateboard manufacturers, skateboard factories, Germany, Australia, Europe, England, Great Britain, Board, skateboard production">
@endpush

@section('content')
	<div class="m-grid__item m-grid__item--fluid m-wrapper">

				
		<div class="m-content">
			<div class="row">
                
				<div class="col-xl-9">
					<div class="m-portlet">
						<div class="m-portlet__head">
							<div class="m-portlet__head-caption">
								<div class="m-portlet__head-title">
									<h3 class="m-portlet__head-text" id="imprint">
										Custom Productions Management Platform
									</h3>
								</div>
							</div>
						</div>
                        
						<div class="m-wizard m-wizard--1 m-wizard--success" id="m_wizard">
							<div class="m-portlet__padding-x"> </div>
								<div class="m-form m-form--label-align-left- m-form--state-">
										<div class="m-form__actions m-form__actions">
											<p>
												<b>Industry 4.0.</b>
											</p>
									<p>
										2HEX connects you with the skateboard production over the internet. 2HEX lets you create your custom products online, automatically forwards your order to the production line, and arranges
										the delivery right to your doorstep. 2HEX lets you manage your productions from your phone - anywhere and at any time.
									</p>


									<img alt="" src="/img/skatefactory-phone-wifi.svg" style="width: 20%" />
										</div>
                            </div>
                        </div>
					</div>
				</div>

                
                <div class="col-xl-9">
					<div class="m-portlet">
						<div class="m-portlet__head">
							<div class="m-portlet__head-caption">
								<div class="m-portlet__head-title">
									<h3 class="m-portlet__head-text" id="privacy">
										Lower prices and better quality than any factory.
									</h3>
								</div>
							</div>
						</div>
                        
						<div class="m-wizard m-wizard--1 m-wizard--success" id="m_wizard">
							<div class="m-portlet__padding-x"> </div>
								<div class="m-form m-form--label-align-left- m-form--state-">
										<div class="m-form__actions m-form__actions">
                                            By merging a large number of productions into one, 2HEX reaches large quantities.
											These quantities are forwarded directly to the production line without first being planned with a sales manager.
											By replacing the factory sales managers and by merging your order with a large number of other productions, 2HEX achieves cheaper production-prices than the factories
											themselves. This enables 2HEX to offer the highest quality below the price of factories' direct sales.

											<br>
                                            <br>
											<a href="https://www.2hex.com/register" class="m-nav__link">Register your own account to see our prices!</a>
                                            <br>
                                        </div>
                            </div>
                        </div>
					</div>
				</div>

				<div class="col-xl-9">
					<div class="m-portlet">
						<div class="m-portlet__head">
							<div class="m-portlet__head-caption">
								<div class="m-portlet__head-title">
									<h3 class="m-portlet__head-text" id="privacy">
										Our Story
									</h3>
								</div>
							</div>
						</div>

						<div class="m-wizard m-wizard--1 m-wizard--success" id="m_wizard">
							<div class="m-portlet__padding-x"> </div>
							<div class="m-form m-form--label-align-left- m-form--state-">
								<div class="m-form__actions m-form__actions">
									It all started in the south of Germany, where a skateboarder graduated from high school and founded a skateboard company.<br>
									<br>
									Being a competitive skateboarder himself, he convinced some of Germany's best skateboarders to join his team and several shops to carry his new brand.
									Not being distracted by the first semesters of university, the skateboarder's company's small manufacturer was soon outgrown and his production machinery was purchased.
									<br>
									<br>
									To make full use of the new production capacities, 'Precision skateboard-factory.com' was founded and blank decks were ordered in bulk from USA and China to receive their custom print
									in the skateboarder's basement.<br>
									<br>
									During his 5th semester, the semester of practical training, the skateboarder was trained as sourcing manager at a Chinese skateboard distribution. Sourcing managers specialize in finding the best factory
									for any production, so the skateboarder started visiting and comparing factories of all skateboard components.
									<br>
									Now working with the best factories and being distributed in Europe and Asia, the skateboarder's brand offered some of the highest quality and best priced skateboard products in the industry.<br>
									<br>
									To make best use of the growing sales in China as well as to strengthen the contact to Chinese factories, the skateboarder returned to China and studied Mandarin. While juggling his skateboard company,
									the skateboard production, the bachelor of business administration in Germany and mandarin studies in China, the founder received an
									invitation with scholarship to HKUST & Cornell MBA - A Master program that only accepted the 100 best young managers across Asia; Preferably in the field of connecting Asia with the West.<br>
									<br>
									The skateboarder asked the Chinese distribution to continue his skateboard company and went back to business school. This time with his full focus, time and the goal to come back stronger than ever.<br>
									<br>
									At these two world class universities, the skateboarder regularly visited the schools of engineering where he co-wrote a whitepaper on industrial automation which received a 135.000 Euro grant from
									the German ministry of commerce, the European Union and the University of Ulm. The skateboarder used the grant, to conduct research on new industrial processes. Some of which would later be used for 2HEX.com
									<br>
									<br>
									In 2019 it all came together: Skateboard Manufacturing, Factory Sourcing and Industrial Automation. By combining all three skills, 2HEX was born.
									Ready to offer the best productions to every skateboarder, founder and manager.
									<br>
									<br>

									<p>
									Now it is your turn: <a href="https://www.2hex.com/register"><b>Register</b> to begin your own story.</a>
									</p>
									<br>
									<br>
									<hr>
									<p>
										Funded by the German Ministry of Economics, the European Union and the University of Ulm School of Computer Science.
									</p>

									<img src="img/exist.png" width="50%">

								</div>
							</div>
						</div>
					</div>
				</div>
                
               
			</div>
		</div>
	</div>
@endsection

resources/views/affiliate.blade.php
@extends('layouts.app')

@section('title', '2HEX SKATEBOARD FACTORY AFFILIATES')

@push('head.meta')
    <meta name="description" content="2HEX skateboard factory. A skateboard manufacturer of skateboard decks, skateboard wheels, skateboard griptapes and high quality complete skateboards.">

	<meta name="keywords" content="2hex, affiliates, affiliate program, skateboard factory affiliate, skateboard manufacturer affiliate, skateboard affiliate, skateboard supplier, skateboard factory, skateboard, manufacturer, supplier, factory, skateboard manufacturers, skateboard factories, 2hex, Germany, Australia, Europe, England, Great Britain, Board, skateboard production">
@endpush

@section('content')
	<div class="m-grid__item m-grid__item--fluid m-wrapper">

				
		<div class="m-content">
			<div class="row">
                
				<div class="col-xl-9">
					<div class="m-portlet">
						<div class="m-portlet__head">
							<div class="m-portlet__head-caption">
								<div class="m-portlet__head-title">
									<h3 class="m-portlet__head-text" id="imprint">
										Affiliate Program
									</h3>
								</div>
							</div>
						</div>
                        
						<div class="m-wizard m-wizard--1 m-wizard--success" id="m_wizard">
							<div class="m-portlet__padding-x"> </div>
								<div class="m-form m-form--label-align-left- m-form--state-">
										<div class="m-form__actions m-form__actions">
                                    <p>
										<b>The 2HEX affiliate program for bloggers and media channels!</b>

									</p>
									<p>
										Earn up to 20% in advertising fees by writing about 2HEX, a trusted skateboard production leader.
									</p>


									<img alt="" src="/img/2hex-affiliate-blogger.jpg" style="width: 100%" />
										</div>
                            </div>
                        </div>
					</div>
				</div>

                
                <div class="col-xl-9">
					<div class="m-portlet">
						<div class="m-portlet__head">
							<div class="m-portlet__head-caption">
								<div class="m-portlet__head-title">
									<h3 class="m-portlet__head-text" id="privacy">
										Join Our Affiliate Program & Make Money With 2HEX
									</h3>
								</div>
							</div>
						</div>
                        
						<div class="m-wizard m-wizard--1 m-wizard--success" id="m_wizard">
							<div class="m-portlet__padding-x"> </div>
								<div class="m-form m-form--label-align-left- m-form--state-">
										<div class="m-form__actions m-form__actions">
                                            Content Sites, Bloggers, Magazines and Networks!<br>
                                            <br>
                                            Join our  affiliate program today. It is easy and free:<br>
                                            1. Let us check your website or blog and receive your custom 2HEX affiliate link.<br>
                                            2. Write an article and add a link to 2HEX<br>
                                            3. Start monetizing your article the same day<br>
                                            <br>
                                            <p>
                                                <b>Get started!</b><br>
                                                Send us your web, magazine or blog address to mail (at) 2hex (dot) com.
                                            </p>
                                        </div>
                            </div>
                        </div>
					</div>
				</div>


                
               
			</div>
		</div>
	</div>
@endsection

resources/views/configurator.blade.php
@extends('layouts.app')

@section('title', 'SKATEBOARD DECKS FACTORY')

@push('head.meta')
    <meta name="description" content="2HEX skateboard decks factory. A skateboard manufacturer of decks, grip tapes, skateboard wheels and high quality complete skateboards">

	<meta name="keywords" content="skateboard decks factory, skateboard decks supplier, skateboard decks manufacturer, skateboard, decks, manufacturer, factory, supplier, skateboard griptape manufacturer, skateboard griptape supplier, 2hex, skateboard wheels manufacturer, skateboard wheels supplier, Germany, Australia, Europe, England, Great Britain, Board, Production.">
@endpush

@section('content')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">
        <skateboard-decks-configurator
            :user="{{ json_encode(auth()->user()) }}"
            :order="{{ json_encode($saved_order ?? null) }}"
            :batchtotal="{{ $orders->sum('quantity') }}"
            :filenames="{{ json_encode($filenames) }}"
        />
    </div>
@endsection

resources/views/mail.blade.php
<h1>Hi, {{ $name }} submit orders</h1>

resources/views/membership.blade.php
@extends('layouts.welcome')

@section('content')
    <div class="title m-b-md">
        Member area
    </div>
    <div class="m-b-md">
        @if($valid)
            Your membership status is confirmed. All the protected pages will be accessible.
            @if($expires)
                <br/>Your license expires on <i>{{  new \Carbon\Carbon($expires) }}</i>
            @endif
        @else
            Your membership status isn't confirmed. All the protected pages will not be accessible!
        @endif

        @if($shopUrl)
            <br/><br/>
            Click <a href="{{ $shopUrl }}">here</a> to extend or renew your membership.
        @endif
    </div>
@endsection

resources/views/summary.blade.php
@extends('layouts.app')

@section('title', 'SKATEBOARD PRODUCTION CONFIGURATOR')

@push('head.meta')
    <meta name="description" content="2HEX skateboard configurator summary. A manufacturer of skateboards, skateboard decks, skateboard wheels, skateboard griptapes and high quality complete skateboards.">

	<meta name="keywords" content="skateboard production configurator, skateboard configurator, skateboard manufacturer, skateboard supplier, skateboard factory, skateboard, manufacturer, supplier, factory, skateboard manufacturers, skateboard factories, 2hex, Germany, Australia, Europe, England, Great Britain, Board, skateboard production">
@endpush

@section('content')
	@php 
		$isAdmin = auth()->check() && auth()->user()->isAdmin();
		setlocale(LC_MONETARY, 'en_US');
	@endphp

	<div class="m-grid__item m-grid__item--fluid m-wrapper">
                    <!-- BEGIN: Subheader -->
		<div class="m-subheader ">
			<div class="d-flex align-items-center">
				<div class="mr-auto">
					<h3 class="m-subheader__title m-subheader__title--separator">ORDER SUMMARY</h3>
					<ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
						<li class="m-nav__item m-nav__item--home">
							<a href="#" class="m-nav__link m-nav__link--icon">
								<i class="m-nav__link-icon la la-home"></i>
							</a>
						</li>
						<li class="m-nav__separator">-</li>
						<li class="m-nav__item">
							<a href="/" class="m-nav__link">
								<span class="m-nav__link-text">Products</span>
							</a>
						</li>
						<li class="m-nav__separator">-</li>
						<li class="m-nav__item">
							<a href="skateboard-manufacturer/skateboard-deck-manufacturer.html" class="m-nav__link">
								<span class="m-nav__link-text">Skateboard Decks</span>
							</a>
						</li>
						<li class="m-nav__separator">-</li>
						<li class="m-nav__item">
							<a href="/skateboard-deck-configurator" class="m-nav__link">
								<span class="m-nav__link-text">Online Order</span>
							</a>
						</li>
                        <li class="m-nav__separator">-</li>
						<li class="m-nav__item">
							<a href="/summary" class="m-nav__link">
								<span class="m-nav__link-text">Summary</span>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
        
        
		<!-- END: Subheader -->
		<div class="m-content">
			
			@if(session()->has('success'))
				<submit-order-modal></submit-order-modal>
				<div 
					class="alert alert-brand m-alert m-alert--icon m-alert--air m-alert--square m--margin-bottom-30" 
					role="alert"
					style="background-color: #008000;"
				>
	                <div class="m-alert__icon">
	                    <i class="flaticon-exclamation-1"></i>
	                </div>
	                <div class="m-alert__text">
	                    {{session()->get('success')}}
	                </div>
	            </div>		
			@endif
            
			<div class="m-portlet">
				<div class="m-portlet__head" style="flex-wrap: wrap;height: auto;float: right;">
					<div class="m-portlet__head-caption">
						<div class="m-portlet__head-title">
						</div>
					</div>
					<div class="m-portlet__head-tools" style="flex-wrap:wrap;">
						@if(Session::get('viewonly') == null)

						<div class="dropdown">
						  	<button 
						  		class="btn m-btn dropdown-toggle dropdown-toggle-split m-btn--gradient-from-primary m-btn--gradient-to-info"
						  		type="button"
						  		data-toggle="dropdown"
						  		aria-haspopup="true" 
						  		aria-expanded="false"
						  		id="actions"
					  		>
						    	Add More
						  	</button>


						  	<div class="dropdown-menu" aria-labelledby="actions">
						  		<a class="dropdown-item" href="{{ route('griptape.index') }}">
						  			Add Griptapes
						  		</a>
						  		<a class="dropdown-item" href="{{ route('get.skateboard.configurator') }}">
						  			Add Decks
						  		</a>
								<a class="dropdown-item" href="{{ route('wheels.configurator') }}">
									Add Wheels
								</a>
						  		@if($isAdmin)
									<a class="dropdown-item" href="{{ route('get.skateboard.configurator') }}">
										Saved Batches
									</a>
								@endif
								
						  	</div>

						</div>

                        <ul class="m-portlet__nav">
							<li class="m-portlet__nav-item">
								<a href="profile#m_user_profile_tab_2" class="btn btn-secondary m-btn m-btn--custom m-btn--icon m-btn--air">
									<span>
										<i class="la la-ship"></i>
										<span>Check Address</span>
									</span>
								</a>
							</li>
						</ul>
                        @endif
                        
					</div>
      
				</div>
				<div class="m-portlet__body">
					<div class="pane pane--table2">
					<table class="table table-striped- table-bordered table-hover table-checkable table-responsive" id="summary-table">
						<tr>
							@if(count($orders) > 0)
								@include('partials.skateboards', ['skateboards' => $orders])
							@endif
							
							@if(count($grips) > 0)
								@include('partials.grips', ['grips' => $grips])
							@endif

							@if(count($wheels) > 0)
								@include('partials.wheels', ['wheels' => $wheels])
							@endif

							<thead style="background-color: #52a3f0; color: white;">
								<tr>
									<td colspan="3">Fixed Cost</td>
									<td colspan="3">Batches</td>
									<td colspan="2">Colors</td>
									<td colspan="5">Filename</td>
									<td>Fixed&nbspTotal</td>
								</tr>
						   	</thead>

                            @foreach($fees as $key => $group)
                            	@foreach($group as $k => $value)
                            		<tr>
										<td colspan="3">{{ $value['type'] }}</td>
										<td colspan="3">{{ $value['batches'] }}</td>
										<td colspan="2">{{ array_key_exists('color', $value) ? $value['color'] : '' }}</td>
										<td colspan="5">{{ $value['image'] }}</td>
										<td>{{ auth()->check() ? money_format('%.2n', $value['price']) : '$?.??' }}</td>
									</tr>
                            	@endforeach
							@endforeach

							@if(! empty($orders->first()->promocode))
								@php 
									$promocode = json_decode($orders->first()->promocode); 
								@endphp
								<tr>
									<td colspan="8">Discount</td>

									<td colspan="5">{{ $promocode->code }}</td>
									<td>{{ $promocode->type == 'fixed' 
										? money_format('-%.2n', $promocode->reward)
										: ($promocode->reward . '%')}}</td>
								</tr>		
							@endif

							<tr>
								<td colspan="16"></td>
							</tr>
						</tr>

					</table>
					</div>

					<!--begin: Datatable (color options: #4CAF50, #586ad5, #8933eb, #52a3f0 or #60bca4) -->
			
					<div class="m-portlet__head" style="padding-left:0;flex-wrap: wrap;">
						<div class="m-portlet__head-caption">
							<div class="m-portlet__head-title" style="padding-left: 20px;">
								<h3 class="m-portlet__head-text">
									USD TOTAL:  {{ auth()->check() ? money_format('%.2n', $totalOrders) : '$?.??' }}
								</h3>
							</div>
						</div>
						<div class="m-portlet__head-tools">
							@if(Session::get('viewonly') != null)
							
							@else
							<ul class="m-portlet__nav">
								
								<!-- <li class="m-portlet__nav-item">
									<a href="{{ route('export.invoice') }}" class="btn btn-secondary m-btn m-btn--custom m-btn--icon" >
										<span>
											<i class="la la-save"></i>
											<span>ExportInvoice</span>
										</span>
									</a>
								</li> -->

								<li class="m-portlet__nav-item">
									<btn-order-later/>
								</li>
								
								<li class="m-portlet__nav-item">
									@php $auth = auth()->user(); @endphp
									
									@if (
										$auth 
										&& strlen($auth->company_name) 
										&& strlen($auth->position) 
										&& strlen($auth->phone_num)
									)
										@php 
											$gripsQuantity = $grips->sum('quantity');
											$wheelsQuantity = $wheels->sum('quantity');
										@endphp

										@if(($gripsQuantity == 0 && $totalOrders > 1170) || ($totalOrders > 1170 && $gripsQuantity > 0))
											<a href="{{ route('orders.submit') }}" class="btn btn-success m-btn m-btn--custom m-btn--icon m-btn--air">
												<span>
													<i class="la la-rocket"></i>
													<span>SUBMIT</span>
												</span>
											</a>
										@else
											@php 
												$message = 'Your order is too small to add custom grip tapes. Please order at least a total of 400 grip tapes or 50 decks to enable grip tapes.';
											@endphp

											@if($wheelsQuantity < 300 && $wheelsQuantity != 0)
												@php 
													$message = 'Your ordered too few wheels to run a custom wheels production. Please order at least 300 sets of wheels.'; 
												@endphp
											@endif
											<a 
												href="javascript:void(0);" 
												class="btn btn-secondary m-btn m-btn--custom m-btn--icon"
												onclick="alert('{{$message}}')"
											>
											<span>
												<i class="la la-rocket"></i>
												<span>SUBMIT</span>
											</span>
										</a>
										@endif
									@else
									<a 
										href="javascript:void(0);" 
										class="btn btn-secondary m-btn m-btn--custom m-btn--icon"
										onclick="alert('Please fill in your complete profile before submitting an order')"
									>
										<span>
											<i class="la la-rocket"></i>
											<span>SUBMIT</span>
										</span>
									</a>
									@endif
								</li>
							</ul>
							@endif
						</div>
					</div>
				</div>
            </div>

            <!-- TOTAL ORDERS QUANTITY LESS 40 -->
            @if($orders->count() && $orders->sum('quantity') <= 40)
				@include('partials.warning-quantity-less')
			@endif

			<!-- VENDOR CODE -->
			@if(!$orders->every->submit && !session()->get('viewonly'))
				@include('partials.vendor-code')
				<!-- <vendor-code /> -->
			@endif
            
			<!-- END EXAMPLE TABLE PORTLET-->
		</div>
	</div>
	<change-name-order-modal></change-name-order-modal>
@endsection