routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');

    // Registration Routes...
    if (config('auth.users.registration')) {
        Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'RegisterController@register');
    }

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.reset.request');

    // Confirmation Routes...
    if (config('auth.users.confirm_email')) {
        Route::get('confirm/{user_by_code}', 'ConfirmController@confirm')->name('confirm');
        Route::get('confirm/resend/{user_by_email}', 'ConfirmController@sendEmail')->name('confirm.send');
    }

    // Social Authentication Routes...
    Route::get('social/redirect/{provider}', 'SocialLoginController@redirect')->name('social.redirect');
    Route::get('social/login/{provider}', 'SocialLoginController@login')->name('social.login');
});

/**
 * Backend routes
 */
// Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

//     // Dashboard
//     Route::get('/', 'DashboardController@index')->name('dashboard');

//     //Users
//     Route::get('users', 'UserController@index')->name('users');
//     Route::get('users/{user}', 'UserController@show')->name('users.show');
//     Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
//     Route::put('users/{user}', 'UserController@update')->name('users.update');
//     Route::get('users/{user}/delete', 'UserController@destroy')->name('users.delete');
//     Route::get('permissions', 'PermissionController@index')->name('permissions');
//     Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');
//     Route::get('dashboard/log-chart', 'DashboardController@getLogChartData')->name('dashboard.log.chart');
//     Route::get('dashboard/registration-chart', 'DashboardController@getRegistrationChartData')->name('dashboard.registration.chart');
// });


Route::get('/', 'HomeController@index')->name('index');
Route::get('/inquiries', 'InquiriesController@index')->name('inquiries');
Route::get('/book', 'BookController@index')->name('book');
Route::get('/profile', 'ProfileController@index')->name('profile');
Route::post('/detail_save', 'ProfileController@detail_save');
Route::post('/address_save', 'ProfileController@store_address');

Route::get('/skateboard-deck-configurator', 'ConfiguratorController@index')->name('get.skateboard.configurator');
Route::get('/skateboard-deck-configurator/{id}', 'ConfiguratorController@show')->name('show.skateboard.configurator');
Route::post('/skateboard-deck-configurator/{id}/copy', 'ConfiguratorController@copy')->name('copy.skateboard.configurator');
Route::get('/skateboard-remove/{id}', 'ConfiguratorController@delete')->name('delete.skateboard.configurator');
Route::post('/skateboard-deck-configurator', 'ConfiguratorController@store');

Route::get('/getdesign','ConfiguratorController@getdesign');
Route::post('/configurator-fileupload', 'ConfiguratorController@upload');

Route::get('/skateboard-deck-manufacturer', 'ManufacturerController@index')->name('skateboard.manufacturer');
Route::get('/export_csv','SummaryController@exportcsv')->name('export.invoice');
Route::get('/export_csv/{id}','SummaryController@exportcsvbyid')->name('export.csv.id');
Route::get('/submit_order','SummaryController@submitOrder')->name('orders.submit');
Route::get('/save_order', 'SummaryController@saveOrder');
Route::get('/remove_saveorder/{id}','SummaryController@removeOrder');
Route::get('/getdata','HomeController@getData');

Route::get('/summary', 'SummaryController@index')->name('summary');
Route::get('/summary/{id}', 'SummaryController@load');
Route::get('/summary/view/{id}', 'SummaryController@view');
Route::get('/imprint', 'ImprintController@index');
Route::get('/ordersuccess', 'OrdersuccessController@index')->name('ordersuccess');
Route::get('/affiliate','AffiliateController@index');
Route::get('/newsletter','NewsController@index')->name('newsletter');
Route::get('/samples','SamplesController@index')->name('samples');
Route::get('/about','AboutController@index')->name('about');
Route::get('/skateboardfaq','SkateboardFAQController@index')->name('skateboardfaq');
Route::get('/invest','investController@index')->name('invest');

Route::get('/skateboard-griptape-manufacturer', 'GripTapeConfigurator@manufacturer')->name('griptape.manufacturer');
Route::get('/grip-tape-configurator', 'GripTapeConfigurator@index')->name('griptape.index');
Route::post('/grip-tape-configurator', 'GripTapeConfigurator@store')->name('griptape.store');
Route::get('/grip-tape-configurator/{id}', 'GripTapeConfigurator@show')->name('griptape.show');
Route::get('/grip-tape-remove/{id}', 'GripTapeConfigurator@destroy')->name('griptape.destroy');
Route::post('/grip-tape-configurator/{id}/copy', 'GripTapeConfigurator@copy')->name('griptape.copy');

/**
 * WHEELS CONFIGURATOR
 */
Route::group(['as' => 'wheels.'], function () {
    Route::get('/skateboard-wheels-manufacturer', 'WheelController@manufacturer')->name('manufacturer');
    Route::get('/skateboard-wheels-configurator', 'WheelController@configurator')->name('configurator');
    Route::get('/skateboard-wheels-configurator/{id}', 'WheelController@show')->name('configurator.show');
    Route::post('/skateboard-wheels-configurator', 'WheelController@storeConfigurator')->name('configurator.store');
    Route::post('/skateboard-wheels-configurator/{id}', 'WheelController@updateConfigurator')->name('configurator.update');
    Route::get('/skateboard-wheels-remove/{id}/', 'WheelController@destroy')->name('configurator.delete');
    Route::post('/skateboard-wheels-configurator/{id}/copy', 'WheelController@copy')->name('configurator.copy');

});

/**
 * HEAT TRANSFERS CONFIGURATOR
 */
Route::group(['as' => 'heat-transfer.'], function () {
    Route::get('/skateboard-heat-transfer-manufacturer', 'HeatTransferController@manufacturer')->name('manufacturer');
    Route::get('/skateboard-heat-transfer-configurator', 'HeatTransferController@configurator')->name('configurator');
});

/**
 * Membership
 */
Route::group(['as' => 'protection.'], function () {
    Route::get('membership', 'MembershipController@index')->name('membership')->middleware('protection:' . config('protection.membership.product_module_number') . ',protection.membership.failed');
    Route::get('membership/access-denied', 'MembershipController@failed')->name('membership.failed');
    Route::get('membership/clear-cache/', 'MembershipController@clearValidationCache')->name('membership.clear_validation_cache');
});


Route::group(['prefix' => 'blog', 'as' => 'blog.', 'middleware' => 'auth'], function () {
    // Route::get('/', 'BlogController@index')->name('index');
    Route::get('/create', 'BlogController@create')->name('create');
    Route::post('/', 'BlogController@store')->name('store');
    Route::delete('/{post}', 'BlogController@destroy')->name('destroy');
    Route::get('/{post}/edit', 'BlogController@edit')->name('edit');
    Route::put('/{post}', 'BlogController@update')->name('update');
});
Route::get('/blog/{id}', 'BlogController@show')->name('blog.show');


Route::post('/vendor-code', 'SummaryController@applyPromocode')->name('vendor.code.apply');

resources/views/partials/batch.blade.php
<li 
    class="m-menu__item  m-menu__item--submenu  m-menu__item--closed m-menu__item--open m-menu__item--active" 
    aria-haspopup="true" 
    m-menu-submenu-toggle="hover"
>
    <a href="javascript:;" class="m-menu__link m-menu__toggle">
        <i class="m-menu__link-bullet m-menu__link-bullet--dot">
            <span></span>
        </i>
        <span class="m-menu__link-text">S.B. Deck Batch </span>
        <i class="m-menu__ver-arrow la la-angle-right"></i>
    </a>
    <div class="m-menu__submenu ">
        <span class="m-menu__arrow"></span>
        <ul class="m-menu__subnav">
            @php $orderPath = null; @endphp
            <li class="m-menu__item" v-bind:class="currentStep == 0 ? 'm-menu__item--active' : ''" aria-haspopup="true" onclick="gotoStep(1, '{{ $orderPath }}')"><a class="m-menu__link "><i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i><span class="m-menu__link-text" >1. Quantity and Size</span></a></li>
            <li class="m-menu__item " v-bind:class="currentStep == 1 ? 'm-menu__item--active' : ''" aria-haspopup="true" onclick="gotoStep(2, '{{ $orderPath }}')"><a class="m-menu__link "><i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i><span class="m-menu__link-text">2. Wood</span></a></li>
            <li class="m-menu__item " v-bind:class="currentStep == 2 ? 'm-menu__item--active' : ''" aria-haspopup="true" onclick="gotoStep(3, '{{ $orderPath }}')"><a class="m-menu__link "><i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i><span class="m-menu__link-text">3. Glue</span></a></li>
            <li class="m-menu__item " v-bind:class="currentStep == 3 ? 'm-menu__item--active' : ''" aria-haspopup="true" onclick="gotoStep(4, '{{ $orderPath }}')"><a class="m-menu__link "><i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i><span class="m-menu__link-text">4. Concave</span></a></li>
            <li class="m-menu__item" v-bind:class="currentStep == 4 ? 'm-menu__item--active' : ''" aria-haspopup="true" onclick="gotoStep(5, '{{ $orderPath }}')"><a class="m-menu__link "><i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i><span class="m-menu__link-text">5. Bottom Print</span></a></li>
            <li class="m-menu__item " v-bind:class="currentStep == 5 ? 'm-menu__item--active' : ''" aria-haspopup="true" onclick="gotoStep(6, '{{ $orderPath }}')"><a class="m-menu__link "><i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i><span class="m-menu__link-text">6. Top Print</span></a></li>
            <li class="m-menu__item " v-bind:class="currentStep == 6 ? 'm-menu__item--active' : ''" aria-haspopup="true" onclick="gotoStep(7, '{{ $orderPath }}')"><a class="m-menu__link "><i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i><span class="m-menu__link-text">7. Engravery</span></a></li>
            <li class="m-menu__item " v-bind:class="currentStep == 7 ? 'm-menu__item--active' : ''" aria-haspopup="true" onclick="gotoStep(8, '{{ $orderPath }}')"><a class="m-menu__link "><i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i><span class="m-menu__link-text">8. Veneer Colors</span></a></li>
            <li class="m-menu__item" v-bind:class="currentStep == 8 ? 'm-menu__item--active' : ''" aria-haspopup="true" onclick="gotoStep(9, '{{ $orderPath }}')"><a class="m-menu__link "><i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i><span class="m-menu__link-text">9. Special</span></a></li>
            <li class="m-menu__item " v-bind:class="currentStep == 9 ? 'm-menu__item--active' : ''" aria-haspopup="true" onclick="gotoStep(10, '{{ $orderPath }}')"><a class="m-menu__link "><i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i><span class="m-menu__link-text">10. Cardboard</span></a></li>
            <li class="m-menu__item " v-bind:class="currentStep == 10 ? 'm-menu__item--active' : ''" aria-haspopup="true" onclick="gotoStep(11, '{{ $orderPath }}')"><a class="m-menu__link "><i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i><span class="m-menu__link-text">11. Box</span></a></li>
        </ul>
    </div>
</li>

resources/views/partials/ga.blade.php
@if (config("analytics.google-analytics") && config("analytics.google-analytics") != "UA-XXXXX-X")
    {{-- Google Analytics: change UA-XXXXX-X to be your site's ID. --}}
    <script>
        (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
                function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
        ga('create','{{ config("analytics.google-analytics") }}','auto');ga('send','pageview');
    </script>
@endif

resources/views/partials/grips.blade.php
    <thead style="background-color: #52a3f0; color: white;">
        <tr>
            <th>Grip Batch</th>
            <th>Pcs</th>
            <th>Size</th>
            <th>Grip Color</th>
            <th>Grit</th>
            <th>Perforation</th>
            <th>Die Cut</th>
            <th>Top Print</th>
            <th>Backpaper</th>
            <th>Backpaper Print</th>
            <th>Carton Print</th>
            <th>Grip Price</th>
            <th>Batch&nbspTotal</th>

            @if(Session::get('viewonly') == null)
            <th>Edit</th>
            @endif

        </tr>
    </thead>
       @foreach($grips as $batch => $grip)

        <tr>
            <td>Griptape Batch #{{++$batch}}</td>
            <td>{{$grip->quantity}}</td>
            <td>{{$grip->size}}</td>
            <td>{{$grip->color}}</td>
            <td>{{$grip->grit}}</td>
            <td>{{$grip->perforation ? 'Yes' : 'None'}}</td>
            <td>{{$grip->die_cut}}</td>
            <td>
                {{$grip->top_print ?? ''}}<br>
                <hr style="border-color: #f4f5f8; margin-left:-3px; margin-right:-5px;">
                <br>
                {{$grip->top_print_color ?? ''}}
            </td>
            <td>{{$grip->backpaper}}</td>
            <td>
                {{$grip->backpaper_print ?? ''}}<br>
                <hr style="border-color: #f4f5f8; margin-left:-3px; margin-right:-5px;">
                <br>
                {{$grip->backpaper_print_color ?? ''}}
            </td>
            <td>
                {{$grip->carton_print ?? ''}}<br>
                <hr style="border-color: #f4f5f8; margin-left:-3px; margin-right:-5px;">
                <br>
                {{$grip->carton_print_color ?? ''}}
            </td>
            <td>{{ auth()->check() ? money_format('%.2n', $grip->price) : '$?.??' }}</td>
            <td>{{ auth()->check() ? money_format('%.2n', $grip->total) : '$?.??' }}</td>

            @if(Session::get('viewonly') == null)
            <td>
                <div class="btn-group" role="group" aria-label="First group">
                    <form action="{{route('griptape.copy', $grip->id)}}" method="POST">
                        {!! csrf_field() !!}
                        <button type="submit" class="m-btn btn btn-secondary" title="Duplicate">
                            <i class="la la-files-o"></i>
                        </button>
                    </form>
                    <form action="{{route('griptape.destroy', $grip->id)}}" method="GET">
                        {!! csrf_field() !!}
                        <button type="submit" class="m-btn btn btn-secondary" title="Delete">
                            <i class="la la-scissors"></i>
                        </button>
                    </form>
                </div>
                <div class="btn-group" role="group" aria-label="First group">
                    <button type="button" class="m-btn btn btn-secondary btn-dev">
                        <i class="la la-floppy-o"></i>
                    </button>
                    <a class="m-btn btn btn-secondary" href="{{route('griptape.show', $grip->id)}}" title="Edit">
                        <i class="la la-italic"></i>
                    </a>
                </div>

                {{--
                <a href="{{route('griptape.show', $grip->id)}}" class="btn btn-outline-info btn-sm">Edit</a>
                <a href="{{route('griptape.show', $grip->id)}}" class="btn btn-outline-info btn-sm">Save</a>
                <a href="{{route('griptape.destroy', $grip->id)}}" class="btn btn-outline-danger btn-sm">Remove</a>
                --}}
            </td>
            @endif
            
        </tr>
        @endforeach

resources/views/partials/skateboards.blade.php
    <thead style="background-color: #52a3f0; color: white;">
        <tr>
            <th>Deck Batch</th>
            <th>Pcs</th>
            <th>Size</th>
            <th>Concave</th>
            <th>Materials</th>
            <th>Print</th>
            <th>Top Engravery</th>
            <th>Veneer&nbspColors</th>
            <th>Specials</th>
            <th>Cardboard Wrap</th>
            <th>Carton Print</th>
            <th>Deck&nbspPrice</th>
            <th>Batch&nbspTotal</th>

            @if(Session::get('viewonly') == null)
            <th>Edit</th>
            @endif

        </tr>
    </thead>
        @foreach($skateboards as $batch => $skateboard)

        <tr>
            <td>Skateboard Deck Batch #{{++$batch}}</td>
            <td>{{$skateboard->quantity}}</td>
            <td>{{$skateboard->size}}</td>
            <td>{{$skateboard->concave}}</td>
            <td>
                <div>
                    <span style="margin-top: 15px; display: block;">
                        {{$skateboard->wood}}<br>
                    </span>
                </div>
                <hr style="border-color: #f4f5f8; margin: 0 -5px 0 -3px">
                <div>
                    <span style="margin-top: 15px; display: block;">
                        {{$skateboard->glue}}<br>
                    </span>
                </div>
            </td>
            <td>
                <div>
                    <span style="margin-top: 15px; display: block;">
                        <b>Bottom</b><br>
                        {{$skateboard->bottomprint ? $skateboard->bottomprint : 'None'}}<br>
                        <hr style="border-color: #f4f5f8; margin: 0 -5px 0 -3px">
                    </span>
                    <span>
                        colors: {{$skateboard->bottomprint_color ?? ''}}
                        <hr style="border-color: #f4f5f8; margin: 0 -5px 0 -3px">
                    </span>
                </div>
                <div>
                    <span style="margin-top: 15px; display: block;">
                        <b>Top</b><br>
                        {{$skateboard->topprint ? $skateboard->topprint : 'None'}}<br>
                        <hr style="border-color: #f4f5f8; margin: 0 -5px 0 -3px">
                    </span>
                    <span>
                        colors: {{$skateboard->topprint_color ?? ''}}
                    </span>
                </div>
            </td>

            <td>{{$skateboard->engravery ? $skateboard->engravery : 'None'}}</td>
            <td>
                <ol style="padding-left:0; list-style-position:inside;">
                    @foreach(json_decode($skateboard->veneer) as $veneer)
                        <li>{{$veneer}}</li>
                    @endforeach 
                </ol>
            </td>
            <td>
                <?php 
                    $count = 0;
                    $extraTitle = [
                        'fulldip' => 'Fulldip',
                        'transparent' => 'Transp. F.dip',
                        'metallic' => 'Metallic dip',
                        'blacktop' => 'Top Fiberglass',
                        'blackmidlayer' => 'Mid Fiberglass',
                        'pattern' => 'Pattern Press',
                    ];
                ?>
                @foreach(json_decode($skateboard->extra) as $key => $extra)
                    @if($extra->state == true)
                        @if($count != 0)
                        <hr style="border-color: #f4f5f8; margin-left:-3px; margin-right:-5px">
                        @endif
                        {{ $extraTitle[$key] }}
                        {{ isset($extra->color) 
                                ? " :" . preg_replace( '/[^0-9a-zA-Z]/', '', $extra->color) 
                                : ' : Yes' 
                        }} 
                        <br>
                        <?php $count ++ ?>
                    @endif
                @endforeach
                <hr style="border-color: #f4f5f8; margin-left:-3px; margin-right:-5px">
                Shrink Wrap: Yes
            </td>
            <td>{{$skateboard->cardboard ? $skateboard->cardboard : 'None'}}</td>
            <td>
                <div>
                    <p style="margin: 30px 0px;">
                        {{$skateboard->carton ? $skateboard->carton : 'None'}}
                        <hr style="border-color: #f4f5f8; margin-left:-3px; margin-right:-5px;">
                    </p>
                    <p>colors: {{$skateboard->carton_color ?? ''}}</p>
                </div>
            </td>

            <td>{{ auth()->check() ? money_format('%.2n', $skateboard->perdeck) : '$?.??' }}</td>
            <td>{{ auth()->check() ? money_format('%.2n', $skateboard->total) : '$?.??' }}</td>
            
            @if(Session::get('viewonly') == null)
                <td>
                    {{--
                    <a href="skateboard-deck-configurator/{{$order->id}}" class="btn btn-outline-info btn-sm">Edit Batch</a>
                    <a href="skateboard-deck-configurator/{{$order->id}}" class="btn btn-outline-info btn-sm">Save Batch</a>
                    <a href="skateboard-deck-configurator/{{$order->id}}" class="btn m-btn--pill btn-outline-success btn-sm">+</a>
                    <a href="skateboard-remove/{{$order->id}}" class="btn m-btn--pill btn-outline-danger btn-sm">-</a>
                    --}}
                    
                    <div class="btn-group" role="group" aria-label="First group">
                        <form action="{{route('copy.skateboard.configurator', $skateboard->id)}}" method="POST">
                            {!! csrf_field() !!}
                            <button type="submit" class="m-btn btn btn-secondary" title="Duplicate">
                                <i class="la la-files-o"></i>
                            </button>
                        </form>
                        <form action="{{route('delete.skateboard.configurator', $skateboard->id)}}" method="GET">
                            {!! csrf_field() !!}
                            <button type="submit" class="m-btn btn btn-secondary" title="Delete">
                                <i class="la la-scissors"></i>
                            </button>
                        </form>
                    </div>
                    <div class="btn-group" role="group" aria-label="First group">
                        <button type="button" class="m-btn btn btn-secondary btn-dev">
                            <i class="la la-floppy-o"></i>
                        </button>
                        <a class="m-btn btn btn-secondary" href="{{route('show.skateboard.configurator', $skateboard->id)}}" title="Edit">
                            <i class="la la-italic"></i>
                        </a>
                    </div>

                </td>
            @endif
        </tr>
        
        @endforeach

resources/views/partials/vendor-code.blade.php
<div class="m-alert m-alert--icon m-alert--air m-alert--square alert alert-dismissible m--margin-bottom-30" role="alert">
	<div class="m-alert__icon">
		<i class="flaticon-businesswoman m--font-brand"></i>
	</div>
	<div class="m-alert__text">
		<form 
			class="m-form m-form--fit m-form--label-align-right" 
			id="vendor-code-form" 
			action="{{ route('vendor.code.apply') }}"
			method="POST" 
		>
			<input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
			<div class="m-portlet__body">
				<div class="row">
					<div class="col-3" style="min-width:150px;">
						<input class="form-control m-input" type="text" value="" placeholder="Vendor Code" name="promocode">
					</div>
					<button type="submit" class="btn btn-secondary m-btn m-btn--icon m-btn--air" id="vendor-code-btn">
						Add
					</button>
				</div>
			</div>
		</form>
	</div>
</div>

resources/views/partials/warning-quantity-less.blade.php
<div class="m-alert m-alert--icon m-alert--air m-alert--square alert alert-dismissible m--margin-bottom-30" role="alert">
	<div class="m-alert__icon">
		<i class="flaticon-exclamation m--font-danger"></i>
	</div>
	<div class="m-alert__text">
        <font style="color: #e35d6f">
        	WARNING: Your total order quantity is less than 50 Decks. 
        	Please add more decks to run a custom production. 
        	For orders of 40 Decks or less we use blank decks from our stock. 
        	This means that you can only choose the decks' width, concave and print.
        </font>
	</div>
</div>

resources/views/partials/wheels.blade.php
    <thead style="background-color: #52a3f0; color: white;">
        <tr>
            <th>Wheels Batch</th>
            <th>Sets</th>
            <th>Style</th>
            <th>Shape</th>
            <th>Size</th>
            <th>Material & Hardness</th>
            <th>Print on Front</th>
            <th>Print on Back</th>
            <th>Wheels Placement</th>
            <th>Cardboard Wrap</th>
            <th>Carton Print</th>
            <th>Set Price</th>
            <th>Batch Total</th>

            @if(Session::get('viewonly') == null)
            <th>Edit</th>
            @endif

        </tr>
    </thead>
       @foreach($wheels as $batch => $wheel)

        <tr>
            <td>Skateboard Wheels Batch #{{++$batch}}</td>
            <td>{{$wheel->quantity}}</td>
            <td>{{$wheel->type}}</td>
            <td>{{$wheel->shape}}</td>
            <td>{{$wheel->size}}</td>
            <td>
                {{$wheel->hardness}}<br>
                <hr style="border-color: #f4f5f8; margin-left:-3px; margin-right:-5px;">
                <br>
                {{$wheel->is_shr ? 'SHR' : ''}}
            </td>
            <td>
                {{$wheel->top_print ?? ''}}<br>
                <hr style="border-color: #f4f5f8; margin-left:-3px; margin-right:-5px;">
                <br>
                colors: {{$wheel->top_colors ?? ''}}
            </td>
            <td>
                {{$wheel->back_print ?? ''}}<br>
                <hr style="border-color: #f4f5f8; margin-left:-3px; margin-right:-5px;">
                <br>
                colors: {{$wheel->back_colors ?? ''}}
            </td>
            <td>{{$wheel->placement}}</td>
            <td>{{$wheel->cardboard_print ?? 'No'}}</td>
            <td>
                {{$wheel->carton_print ?? ''}}<br>
                <hr style="border-color: #f4f5f8; margin-left:-3px; margin-right:-5px;">
                <br>
                colors: {{$wheel->cardboard_colors ?? ''}}
            </td>
            <td>{{ auth()->check() ? money_format('%.2n', $wheel->price) : '$?.??' }}</td>
            <td>{{ auth()->check() ? money_format('%.2n', $wheel->total) : '$?.??' }}</td>

            @if(Session::get('viewonly') == null)
            <td>
                <div class="btn-group" role="group" aria-label="First group">
                    <form action="{{route('wheels.configurator.copy', $wheel->wheel_id)}}" method="POST">
                        {!! csrf_field() !!}
                        <button type="submit" class="m-btn btn btn-secondary" title="Duplicate">
                            <i class="la la-files-o"></i>
                        </button>
                    </form>
                    <form action="{{route('wheels.configurator.delete', $wheel->wheel_id)}}" method="GET">
                        {!! csrf_field() !!}
                        <button type="submit" class="m-btn btn btn-secondary" title="Delete">
                            <i class="la la-scissors"></i>
                        </button>
                    </form>
                </div>
                <div class="btn-group" role="group" aria-label="First group">
                    <button type="button" class="m-btn btn btn-secondary btn-dev">
                        <i class="la la-floppy-o"></i>
                    </button>
                    <a class="m-btn btn btn-secondary" href="{{route('wheels.configurator.show', $wheel->wheel_id)}}" title="Edit">
                        <i class="la la-italic"></i>
                    </a>
                </div>

            </td>
            @endif

        </tr>
        @endforeach