routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');

    // Registration Routes...
    if (config('auth.users.registration')) {
        Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'RegisterController@register');
    }

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.reset.request');

    // Confirmation Routes...
    if (config('auth.users.confirm_email')) {
        Route::get('confirm/{user_by_code}', 'ConfirmController@confirm')->name('confirm');
        Route::get('confirm/resend/{user_by_email}', 'ConfirmController@sendEmail')->name('confirm.send');
    }

    // Social Authentication Routes...
    Route::get('social/redirect/{provider}', 'SocialLoginController@redirect')->name('social.redirect');
    Route::get('social/login/{provider}', 'SocialLoginController@login')->name('social.login');
});

/**
 * Backend routes
 */
// Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

//     // Dashboard
//     Route::get('/', 'DashboardController@index')->name('dashboard');

//     //Users
//     Route::get('users', 'UserController@index')->name('users');
//     Route::get('users/{user}', 'UserController@show')->name('users.show');
//     Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
//     Route::put('users/{user}', 'UserController@update')->name('users.update');
//     Route::get('users/{user}/delete', 'UserController@destroy')->name('users.delete');
//     Route::get('permissions', 'PermissionController@index')->name('permissions');
//     Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');
//     Route::get('dashboard/log-chart', 'DashboardController@getLogChartData')->name('dashboard.log.chart');
//     Route::get('dashboard/registration-chart', 'DashboardController@getRegistrationChartData')->name('dashboard.registration.chart');
// });


Route::get('/', 'HomeController@index')->name('index');
Route::get('/inquiries', 'InquiriesController@index')->name('inquiries');
Route::get('/book', 'BookController@index')->name('book');
Route::get('/profile', 'ProfileController@index')->name('profile');
Route::post('/detail_save', 'ProfileController@detail_save');
Route::post('/address_save', 'ProfileController@store_address');

Route::get('/skateboard-deck-configurator', 'ConfiguratorController@index')->name('get.skateboard.configurator');
Route::get('/skateboard-deck-configurator/{id}', 'ConfiguratorController@show')->name('show.skateboard.configurator');
Route::post('/skateboard-deck-configurator/{id}/copy', 'ConfiguratorController@copy')->name('copy.skateboard.configurator');
Route::get('/skateboard-remove/{id}', 'ConfiguratorController@delete')->name('delete.skateboard.configurator');
Route::post('/skateboard-deck-configurator', 'ConfiguratorController@store');

Route::get('/getdesign','ConfiguratorController@getdesign');
Route::post('/configurator-fileupload', 'ConfiguratorController@upload');

Route::get('/skateboard-deck-manufacturer', 'ManufacturerController@index')->name('skateboard.manufacturer');
Route::get('/export_csv','SummaryController@exportcsv')->name('export.invoice');
Route::get('/export_csv/{id}','SummaryController@exportcsvbyid')->name('export.csv.id');
Route::get('/submit_order','SummaryController@submitOrder')->name('orders.submit');
Route::get('/save_order', 'SummaryController@saveOrder');
Route::get('/remove_saveorder/{id}','SummaryController@removeOrder');
Route::get('/getdata','HomeController@getData');

Route::get('/summary', 'SummaryController@index')->name('summary');
Route::get('/summary/{id}', 'SummaryController@load');
Route::get('/summary/view/{id}', 'SummaryController@view');
Route::get('/imprint', 'ImprintController@index');
Route::get('/ordersuccess', 'OrdersuccessController@index')->name('ordersuccess');
Route::get('/affiliate','AffiliateController@index');
Route::get('/newsletter','NewsController@index')->name('newsletter');
Route::get('/samples','SamplesController@index')->name('samples');
Route::get('/about','AboutController@index')->name('about');
Route::get('/skateboardfaq','SkateboardFAQController@index')->name('skateboardfaq');
Route::get('/invest','investController@index')->name('invest');

Route::get('/skateboard-griptape-manufacturer', 'GripTapeConfigurator@manufacturer')->name('griptape.manufacturer');
Route::get('/grip-tape-configurator', 'GripTapeConfigurator@index')->name('griptape.index');
Route::post('/grip-tape-configurator', 'GripTapeConfigurator@store')->name('griptape.store');
Route::get('/grip-tape-configurator/{id}', 'GripTapeConfigurator@show')->name('griptape.show');
Route::get('/grip-tape-remove/{id}', 'GripTapeConfigurator@destroy')->name('griptape.destroy');
Route::post('/grip-tape-configurator/{id}/copy', 'GripTapeConfigurator@copy')->name('griptape.copy');

/**
 * WHEELS CONFIGURATOR
 */
Route::group(['as' => 'wheels.'], function () {
    Route::get('/skateboard-wheels-manufacturer', 'WheelController@manufacturer')->name('manufacturer');
    Route::get('/skateboard-wheels-configurator', 'WheelController@configurator')->name('configurator');
    Route::get('/skateboard-wheels-configurator/{id}', 'WheelController@show')->name('configurator.show');
    Route::post('/skateboard-wheels-configurator', 'WheelController@storeConfigurator')->name('configurator.store');
    Route::post('/skateboard-wheels-configurator/{id}', 'WheelController@updateConfigurator')->name('configurator.update');
    Route::get('/skateboard-wheels-remove/{id}/', 'WheelController@destroy')->name('configurator.delete');
    Route::post('/skateboard-wheels-configurator/{id}/copy', 'WheelController@copy')->name('configurator.copy');

});

/**
 * HEAT TRANSFERS CONFIGURATOR
 */
Route::group(['as' => 'heat-transfer.'], function () {
    Route::get('/skateboard-heat-transfer-manufacturer', 'HeatTransferController@manufacturer')->name('manufacturer');
    Route::get('/skateboard-heat-transfer-configurator', 'HeatTransferController@configurator')->name('configurator');
});

/**
 * Membership
 */
Route::group(['as' => 'protection.'], function () {
    Route::get('membership', 'MembershipController@index')->name('membership')->middleware('protection:' . config('protection.membership.product_module_number') . ',protection.membership.failed');
    Route::get('membership/access-denied', 'MembershipController@failed')->name('membership.failed');
    Route::get('membership/clear-cache/', 'MembershipController@clearValidationCache')->name('membership.clear_validation_cache');
});


Route::group(['prefix' => 'blog', 'as' => 'blog.', 'middleware' => 'auth'], function () {
    // Route::get('/', 'BlogController@index')->name('index');
    Route::get('/create', 'BlogController@create')->name('create');
    Route::post('/', 'BlogController@store')->name('store');
    Route::delete('/{post}', 'BlogController@destroy')->name('destroy');
    Route::get('/{post}/edit', 'BlogController@edit')->name('edit');
    Route::put('/{post}', 'BlogController@update')->name('update');
});
Route::get('/blog/{id}', 'BlogController@show')->name('blog.show');


Route::post('/vendor-code', 'SummaryController@applyPromocode')->name('vendor.code.apply');

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Post;
use App\Scopes\SearchScope;
use Validator;

class BlogController extends Controller
{
	public function index(Request $request)
    {
    	$posts = Post::query()
    		->withGlobalScope('search', new SearchScope($request))
    		->get();

		return $posts;
    }

    public function show($slug)
    {
        $post = Post::query()
            ->with('author')
            ->where('slug', $slug)
            ->firstOrFail();

    	return view('blog.show', compact('post'));
    } 

    public function create()
    {
        return view('blog.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title'   => 'required|string',
            'image'   => 'required', 
            'content' => 'required', 
        ]);

        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }

        $data = $validator->getData();

        $data['user_id'] = auth()->id();
        $data['active'] = array_key_exists('active', $data) ? true : false;

        Post::create($data);

        return redirect('/')->with('message', 'You success created new post!');
        
    }

    public function destroy(Post $post)
    {
        $post->delete();

        return redirect('/')->with('message', 'You success deleted post!');

    }

    public function update(Request $request, Post $post)
    {
        $validator = Validator::make($request->all(), [
            'title'   => 'required|string',
            'image'   => 'required', 
            'content' => 'required', 
            'active'  => 'nullable', 
        ]);

        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }
        $data = $validator->getData();
        $data['active'] = array_key_exists('active', $data) ? true : false;

        $post->update($data);

        return back()->with('message', 'You success updated post!');
    }

    public function edit(Post $post)
    {
        return view('blog.create', compact('post'));
    }
}

resources/views/blog/create.blade.php
@extends('layouts.app')
@push('head.styles')
	<style>
		.upload-btn-wrapper {
		    position: relative;
		    overflow: hidden;
		}

		.upload-btn {
		    border: 2px solid gray;
		    color: gray;
		    background-color: white;
		    padding: 8px 20px;
		    border-radius: 8px;
		    font-size: 20px;
		    font-weight: bold;
		}

		.upload-btn-wrapper input[type=file] {
		    font-size: 100px;
		    position: absolute;
		    left: 0;
		    top: 0;
		    opacity: 0;
		    width: 100%;
		}
	</style>
@endpush
@push('head.scripts')
    <script src="https://cloud.tinymce.com/5/tinymce.min.js?apiKey=re1puig8wwns5dt6o4ys4k2pmzmltdnmw4xhbctutrdcazl4"></script>
    <script>
		tinymce.init({
		    selector: '#content',
		    plugins : 'autolink link image imagetools lists charmap preview table emoticons checklist wordcount advcode',
		    toolbar: "numlist bullist checklist emoticons wordcount code",
		    images_upload_url : '/upload.php',
		    automatic_uploads : false,
		    relative_urls: false,
		    min_height: 500,
		    entity_encoding: "numeric", 

			images_upload_handler: function (blobInfo, success, failure) {
				var xhr, formData;

				xhr = new XMLHttpRequest();
				xhr.withCredentials = false;
				xhr.open('POST', '/upload.php');

				xhr.onload = function() {
				  var json;

				  if (xhr.status < 200 || xhr.status >= 300) {
					failure('HTTP Error: ' + xhr.status);
					return;
				  }

				  json = JSON.parse(xhr.responseText);

				  if (!json || typeof json.location != 'string') {
					failure('Invalid JSON: ' + xhr.responseText);
					return;
				  }

				  success(json.location);
				};

				formData = new FormData();
				formData.append('file', blobInfo.blob(), blobInfo.filename());

				xhr.send(formData);
			}
		});

  </script>
@endpush

@section('content')
	@php 
		$isEdit = isset($post);
		$action = $isEdit ? route('blog.update', $post->id) : route('blog.store');
	@endphp

	<div class="m-grid__item m-grid__item--fluid m-wrapper">
		<div class="m-content">
			@if ($errors->any())
			 	<div class="alert alert-danger" role="alert">
			  		<ul>
			     		@foreach ($errors->all() as $error)
			  				<li><span>{{$error}}</span></li>
			     		@endforeach
			  		</ul>
				</div>
			@endif
            @if(session()->has('message'))
                <div class="alert alert-success">
                {{ session()->get('message')}}
                </div>
            @endif
			<div class="row">
				<div class="col-xl-12">
					<div class="m-portlet">
						<div class="m-portlet__head">
							<div class="m-portlet__head-caption">
								<div class="m-portlet__head-title">
									<h3 class="m-portlet__head-text" id="imprint">
										Page creation a new post
									</h3>
								</div>
								@if($isEdit)
									<div class="m-portlet__head-title">
										<a class="btn btn-link" href="{{ route('blog.show', $post->slug) }}">Show post</a>
									</div>
								@endif
								
							</div>
						</div>

                        <form method="POST" action="{{ $action }}" enctype="multipart/form-data"> 
                        	{{ csrf_field() }}

                        	@if($isEdit)
								{{ method_field('PUT') }}
							@endif

							<input type="hidden" id="image" name="image" value="{{ $isEdit ? $post->image : '' }}">

							<div class="container">
								<div class="row">
									<div class="col-md-8">
									  	<div class="form-group">
									    	<label for="title">Title</label>
									    	<input 
									    		type="text" 
									    		class="form-control" 
									    		id="title" 
									    		name="title" 
									    		placeholder="Enter title"
									    		value="{{$isEdit ? $post->title : ''}}"
								    		>
									  	</div>
										<div class="custom-control custom-checkbox mb-3">
										  	<input 
										    	type="checkbox" 
										    	class="custom-control-input" 
										    	id="active" 
										    	name="active"
									    	>
										  	<label class="custom-control-label" for="active">Active</label>
										</div>
										<div class="form-group">
										    <label for="content">Content</label>
										    <textarea name="content" id="content">
										    </textarea>
										</div>
										<div class="form-group">
											@if($isEdit)
											<button type="submit" class="btn btn-primary">Update</button>
											@else
												<button type="submit" class="btn btn-primary">Submit</button>
											@endif
										</div>
									</div>
									<div class="col-md-4">
										<div class="panel panel-default">
									        <label class="panel-heading">Preview image:</label>
									        <div class="upload-btn-wrapper">
											  	<button class="upload-btn" >Upload a file</button>
											  	<input type="file" accept="image/*" onchange="loadPreview(event)"/>
											</div>
									        <img id='output' height="100" class="mt-4" src="{{ $isEdit ? $post->image : '' }}"/>
									    </div>
									</div>
								</div>
	                        </div>
						</form>

					</div>
				</div>   
			</div>
		</div>
	</div>

@endsection

@push('footer.scripts')
	<script>
		@if (isset($post))
			$('#content').html('{!! $post->content !!}');
			$('#active').prop('checked', "{{ $post->active }}" == true ? true : false);
		@else
			$('#active').prop('checked', true);
		@endif
		

		var loadPreview = function(event) {
			event.preventDefault();
			var formData, file;
	    	var output = document.getElementById('output');
	    	// var imageInput = document.getElementById('image');

	    	var xhr = new XMLHttpRequest();
			xhr.open("POST", "/upload.php");
			xhr.onload = function() {
			  	var json;

			  	if (xhr.status < 200 || xhr.status >= 300) {
					failure('HTTP Error: ' + xhr.status);
					return;
			  	}

			  	json = JSON.parse(xhr.responseText);

			  	if (!json || typeof json.location != 'string') {
					failure('Invalid JSON: ' + xhr.responseText);
					return;
			  	}
		    	output.src = json.location;
		    	document.getElementById("image").value = json.location;
			}
			formData = new FormData();
			file = event.target.files[0];
			formData.append('file', file, file.name);
			xhr.send(formData);
		};
	</script>
@endpush

resources/views/blog/show.blade.php
@extends('layouts.app')

@section('title', 'SKATEBOARD MANUFACTURER BLOG')

@push('head.meta')
    <meta name="description" content="2HEX skateboard manufacturer blog. {{$post->title}}">

	<meta name="keywords" content="{{$post->title}}, skateboard manufacturer blog, skateboard factory blog, skateboard supplier blog, skateboard company blog, skateboard company founder, how to start a skateboard company, how to build a skateboard company, how to found a skateboard company, skateboard decks manufacturer, skateboard decks supplier, skateboard decks factory, skateboard, decks, manufacturer, factory, supplier, skateboard griptape manufacturer, skateboard griptape supplier, 2hex, skateboard wheels manufacturer, skateboard wheels supplier, Germany, Australia, Europe, England, Great Britain, Board, Production.">
@endpush

@push('head.styles')
	<style>
		.r-side-flex {
		    display: -webkit-box;
		    display: -ms-flexbox;
		    display: flex;
		    -webkit-box-orient: vertical;
		    -webkit-box-direction: normal;
		        -ms-flex-direction: column;
		            flex-direction: column;
		    position: fixed;
		}
		.r-side-flex .btn {
		    margin: 5px;
		}
	</style>
@endpush
@section('content')
	<div class="m-grid__item m-grid__item--fluid m-wrapper">
		<div class="m-content">
			<div class="row">
				<div class="col-md-9">
					<div class="m-portlet">
						<div class="m-portlet__head">
							<div class="m-portlet__head-caption">
								<div class="m-portlet__head-title">
									<h1 class="m-portlet__head-text" id="imprint">
										The Skateboard Manufacturer Blog
									</h1>
								</div>
							</div>
						</div>
                                    
						<div class="m-wizard m-wizard--1 m-wizard--success" id="m_wizard">
							<div class="m-portlet__padding-x"></div>
							<div class="m-form m-form--label-align-left- m-form--state-">
								<div class="m-form__actions m-form__actions">
                                    <img 
                                    	src="{{ $post->image }}" 
                                    	style="width: 100%"
                                	>
									<br>
                                    <h2 class="m-portlet__head-text mt-5" id="imprint">
                                         {{$post->title}}
                                    </h2>
									<p>{!! html_entity_decode($post->content) !!}</p>                                          
                                </div>
                            </div>
                        </div>
					</div>
				</div>   
				@if(auth()->check() && auth()->user()->isAdmin())
					<div class="col-md-3">
						<form action="{{ route('blog.destroy', $post->id) }}" method="POST" class="r-side-flex">
			                {{ csrf_field() }}
			                {{ method_field('DELETE') }}
							<a href="{{ route('blog.create') }}" class="btn btn-outline-success">New Post</a>
							<a href="{{ route('blog.edit', $post->id) }}" class="btn btn-outline-warning">Edit</a>
			                <button type="submit" class="btn btn-outline-danger">Remove</button>
			            </form>
					</div>
				@endif
			</div>
		</div>
	</div>
@endsection